### ISSUE TITLE
Build of tiger-test-lib fail in TestTigerDirector 

### ISSUE THREAD

**Issue by Thopap** [gematik/app-Tiger#1]
I am trying to build the tiger, but currently fail in TestTigerDirector with a certificate issue?

`07:34:20.976 [main] WARN de.gematik.test.tiger.lib.TigerDirector - ABORTING initialisation as environment variable TIGER_ACTIVE is not set to '1'
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.605 s <<< FAILURE! - in de.gematik.test.tiger.lib.TestTigerDirector
[ERROR] de.gematik.test.tiger.lib.TestTigerDirector.testDirectorSimpleIdp  Time elapsed: 7.593 s  <<< ERROR!
de.gematik.test.tiger.testenvmgr.TigerTestEnvException: Unable to pull image gstopdr1.top.local/idp/idp-server:17.0.0-38!
        at de.gematik.test.tiger.lib.TestTigerDirector.testDirectorSimpleIdp(TestTigerDirector.java:53)
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException:
Status 500: {"message":"Get https://gstopdr1.top.local/v2/: x509: certificate signed by unknown authority"}

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   TestTigerDirector.testDirectorSimpleIdp:53 » TigerTestEnv Unable to pull image...
[INFO]
[ERROR] Tests run: 44, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for app-Tiger 0.5.0:
[INFO]
[INFO] app-Tiger .......................................... SUCCESS [  3.608 s]
[INFO] tiger-common ....................................... SUCCESS [ 22.810 s]
[INFO] tiger-proxy ........................................ SUCCESS [01:18 min]
[INFO] tiger-standalone-proxy ............................. SUCCESS [ 53.001 s]
[INFO] tiger-testenv-mgr .................................. SUCCESS [03:07 min]
[INFO] tiger-test-lib ..................................... FAILURE [ 35.663 s]
[INFO] tiger-aforeporter-plugin ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:21 min
[INFO] Finished at: 2021-07-07T07:34:21+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project tiger-test-lib: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Dev\projects\epa\app-Tiger\tiger-test-lib\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :tiger-test-lib`

**Comment by Arkinator** [comment]
Thanks you for raising this issue and sry about the delay in response time. We have openend an internal ticket for this matter.
(If you only want to use the tiger-proxy the full build is unnecessary. The bug is valid and annoying at any rate and will be fixed)

**Comment by Arkinator** [comment]
Issue was solved a long time ago, the ticket simply survived as a zombie. closed.
