### ISSUE TITLE
Running a Standalone tiger Proxy not possible

### ISSUE THREAD

**Issue by Thopap** [gematik/app-Tiger#2]
From the documentation (https://github.com/gematik/app-Tiger/tree/master/tiger-standalone-proxy) it is currently not quiet clear howto create a running proxy. I tried several approaches:  

I tried the following approaches after a `mvn clean install`
1. Using `docker build .` , since the application folder contain a Dockerfile.
Docker build was successful, but the produced image failed to start with `Error: Unable to access jarfile tiger-proxy.jar`

2. As a standalone application using simple `java -jar .\target\tiger-standalone-proxy-0.5.0.jar`
this just produce `no main manifest attribute, in .\target\tiger-standalone-proxy-0.5.0.jar`

3. Run a standalone application with the application name `java -cp .\target\tiger-standalone-proxy-0.5.0.jar de.gematik.test.tiger.proxy.TigerStandaloneProxyApplication`
This just produce `Error: Unable to initialize main class de.gematik.test.tiger.proxy.TigerStandaloneProxyApplication
Caused by: java.lang.NoClassDefFoundError: de/gematik/test/tiger/proxy/TigerProxy`

4. Using spring boot `mvn spring-boot:image-build` and afterwards a `docker run --rm -p  6666:6666 --env ROUTES="http://not.a.real.server;http://google.com" docker.io/library/tiger-standalone-proxy:0.5.0`
Now the image starts, but when trying to use the curl example the connection is simply aborted:
`$ curl https://gog --proxy localhost:6666 -vv --insecure
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:6666...
* TCP_NODELAY set
* Connected to localhost (::1) port 6666 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to gog:443
> CONNECT gog:443 HTTP/1.1
> Host: gog:443
> User-Agent: curl/7.68.0
> Proxy-Connection: Keep-Alive
>
* Proxy CONNECT aborted
* CONNECT phase completed!
* Closing connection 0
curl: (56) Proxy CONNECT aborted
`

and the container logs:
`
....
2021-07-07 06:27:28.337 INFO 1 --- [ main] o.s.b.a.ApplicationAvailabilityBean : Application availability state ReadinessState changed to ACCEPTING_TRAFFIC

2021-07-07 06:28:26.871 INFO 1 --- [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats : WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
`

Also loading the log page `http://localhost:6666/rbel` does not display something in the browser.

Can you please provide some guidance what might be wrong?

**Comment by Arkinator** [comment]
- The intended avenue for usage would be java -jar on the shaded spring-boot jar (https://repo1.maven.org/maven2/de/gematik/test/tiger-standalone-proxy/0.8.1/tiger-standalone-proxy-0.8.1.jar)
- The tiger-proxy always needs TWO ports: one is the actual proxy-server, the other the accompanying spring-boot-server. The spring-boot server offers a rest-service for live-configuration and also the tracing/traffic-endpoints. The two properties are named `server.port` for the spring-boot server and `tigerProxy.port` for the proxy-server.
- Since the version 0.5.0 the live-view was changed to http://localhost:<server.port>/webui

Hope this helps, sry about the wait.

Regards
